// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsjgdlkomxybqunxwvqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzamdkbGtvbXh5YnF1bnh3dnFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTU3NDMsImV4cCI6MjA3NDI5MTc0M30.EsxlnMs_Ppzz7bYTRhHOHg23cDJdPcpbYmivzv566b8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});